class BuyPage {

    buy(size, color, size2, color2, size3, color3, size4, color4){
        cy.get('#primary-menu > .menu-item-629 > a').click()
        cy.get('.post-2559 > .product-block > .block-inner > .image > .product-image > .image-hover').click()
        cy.get('.button-variable-item-' + size).click()
        cy.get('.button-variable-item-' + color).click()
        cy.get('.input-text').clear().type('1')
        cy.get('.single_add_to_cart_button').click()
        cy.get('#primary-menu > .menu-item-629 > a').click()
        cy.get('.post-3964 > .product-block > .block-inner > .image > .product-image > .image-hover').click()
        cy.get('.button-variable-item-' + size2).click()
        cy.get('.button-variable-item-' + color2).click()
        cy.get('.single_add_to_cart_button').click()
        cy.get('#primary-menu > .menu-item-629 > a').click()
        cy.get(':nth-child(3) > .page-numbers').click()
        cy.get('.post-3745 > .product-block > .block-inner > .image > .product-image > .image-hover').click()
        cy.get('.button-variable-item-' + size3).click()
        cy.get('.button-variable-item-' + color3).click()
        cy.get('.single_add_to_cart_button').click()
        cy.get('#primary-menu > .menu-item-629 > a').click()
        cy.get(':nth-child(7) > .page-numbers').click()
        cy.get('.post-3006 > .product-block > .block-inner > .image > .product-image > .image-hover').click()
        cy.get('.button-variable-item-' + size4).click()
        cy.get('.button-variable-item-' + color4).click()
        cy.get('.single_add_to_cart_button').click()
        cy.get('.woocommerce-message > .button').click()
        cy.get('.checkout-button').click()
        cy.get('#terms').click()
      //  cy.get('.woocommerce-terms-and-conditions-wrapper > .form-row').find('[type="checkbox"]').check()
        cy.get('#place_order').click()
    }
}

export default new BuyPage()